import { COMPLAINT_STATUS, Comment, PRODUCT_STATUS } from '@prisma/client';

export interface IPaginatedComplaints {
  complaints: IComplaint[];
  limit: number;
  page: number;
  totalPages: number;
  totalRecords: number;
}

// Generated by https://quicktype.io

export interface IComplaint {
  id: string;
  description: string;
  userId: string;
  orderId: string;
  createdAt: Date;
  updatedAt: Date;
  status: COMPLAINT_STATUS;
  resolvedById?: string;
  comments: Comment[];
  faultyItems: any[];
  user: User;
  order: Order;
  resolvedBy?: IResolvedBy;
}

export interface IResolvedBy {
  id: string;
  username: string;
  password: string;
  name: string;
  email: string;
  phone_number: string;
  emailVerified: null;
  role: string;
  applyingAsBusinessClient: boolean;
  image: string;
  shopAddress: null;
  taxId: null;
}

export interface FaultyItem {
  id: string;
  description: null;
  orderItemId: string;
  createdAt: string;
  updatedAt: string;
  complaintId: string;
}

export interface Order {
  id: string;
  orderNumber: number;
  totalPrice: number;
  userId: string;
  createdAt: string;
  updatedAt: string;
  deliveryCharge: number;
  status: string;
  paymentStatus: string;
  selectedWholesaleOption: string;
  paymentMethod: string;
  customerAddress: string;
  additionalPhoneNumber: string;
  partiallyPaidAmount: number;
  amountLeftToPay: number;
  partialPaymentTime: string;
}

export interface User {
  id: string;
  username: string;
  password: string;
  name: string;
  email: string;
  phone_number: string;
  emailVerified: null;
  role: string;
  applyingAsBusinessClient: boolean;
  image: string;
  shopAddress: null;
  taxId: null;
}
